USE [PFADW_META]
GO


drop TABLE [dbo].[SQLOBJECTDEPENDENCIES]
Go

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SQLOBJECTDEPENDENCIES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[SQLObjectDependencies](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[DBINSTANCE] [nvarchar](255) NULL,
	[DBNAME] [nvarchar](255) NULL,
	[SQLID] [nvarchar](255) NULL,
	[SQLOBJECT] [nvarchar](255) NULL,
	[OPERATION] [nvarchar](255) NULL,
	[NODES_SELECTION] [nvarchar](255) NULL,
	[IDENTS] [nvarchar](255) NULL,
	[REFINSTANCE] [nvarchar](255) NULL,
	[REFDB] [nvarchar](255) NULL,
	[REFSCHEMA] [nvarchar](255) NULL,
	[REFOBJECTNAME] [nvarchar](255) NULL,
	[REFOBJECTTYPE] [nvarchar](255) NULL,
	[SysCreated] [datetime2](7) NULL,
	[SysCreatedBy] [nvarchar](50) NULL,
	[SysCreatedHost] [nvarchar](50) NULL,
 CONSTRAINT [PK_SQLObjectDependencies] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_SQLOBJECTDEPENDENCIES_SysCreated]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SQLOBJECTDEPENDENCIES] ADD  CONSTRAINT [DF_SQLOBJECTDEPENDENCIES_SysCreated]  DEFAULT (getutcdate()) FOR [SysCreated]
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_SQLOBJECTDEPENDENCIES_SysCreatedBy]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SQLOBJECTDEPENDENCIES] ADD  CONSTRAINT [DF_SQLOBJECTDEPENDENCIES_SysCreatedBy]  DEFAULT (suser_sname()) FOR [SysCreatedBy]
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_SQLOBJECTDEPENDENCIES_SysCreatedHost]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SQLOBJECTDEPENDENCIES] ADD  CONSTRAINT [DF_SQLOBJECTDEPENDENCIES_SysCreatedHost]  DEFAULT (host_name()) FOR [SysCreatedHost]
END
GO


